- hosts: localhost
  connection: local
  become: yes

  tasks:

  - name: Deploy website
    copy:
      src: index2.html
      dest: /var/www/html/index2.html

  - name: Restart Apache
    service:
      name: apache2
      state: restarted
